[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = 'source $HOME/.vim/rc/plugins/vimshell.rc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'source $HOME/.vim/rc/plugins/unite.rc.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = 'source $HOME/.vim/rc/plugins/vim-ref.rc.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = 'source $HOME/.vim/rc/plugins/syntastic.rc.vim'
