[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = [ 'unite.vim', 'vimshell.vim' ]

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = 'source $HOME/.vim/rc/plugins/neocomplete.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = [
  'neosnippet-snippets',
  'context_filetype.vim'
] 
on_event = 'InsertCharPre'
hook_source = 'source $HOME/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = [ 'html' ]

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = [ 'css' ]

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = 'tomasr/molokai'
