[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = [ 'unite.vim', 'vimshell.vim' ]

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = 'source $HOME/.vim/rc/plugins/unite.rc.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'
depends = 'unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = 'source $HOME/.vim/rc/plugins/neocomplete.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = [
  'neosnippet-snippets',
  'context_filetype.vim'
] 
on_event = 'InsertCharPre'
hook_source = 'source $HOME/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = [ 'html' ]

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = [ 'css' ]

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = [ 'js', 'jsx' ]

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = [ 'jsx' ]
hook_source = '''
  let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'
on_ft = [ 'js', 'jsx' ]

[[plugins]]
repo = 'vim-scripts/vim-stylus'
on_ft = [ 'styl', 'stylus' ]

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = 'lervag/vimtex'
on_ft = [ 'tex' ]
hook_add = 'source $HOME/.vim/rc/plugins/vimtex.rc.vim'

[[plugins]]
repo = 'tomasr/molokai'


# reStructuredText for sphinx
[[plugins]]
repo = 'Rykka/clickable.vim'

[[plugins]]
repo = 'Rykka/riv.vim'
depends = 'clickable.vim'
on_ft = [ 'rst' ]

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = [ 'c', 'cpp' ]

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_i = 1
on_ft = [ 'py' ]

# pip install jedi
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_i = 1
on_ft = [ 'py' ]
hook_source = 'source $HOME/.vim/rc/plugins/jedi-vim.rc.vim'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = [ 'py' ]

