[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = 'source $HOME/.vim/rc/plugins/vimshell.rc.vim'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = 'source $HOME/.vim/rc/plugins/vim-ref.rc.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = 'source $HOME/.vim/rc/plugins/syntastic.rc.vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = [ 'ts', 'tsx' ]

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = [ 'ts', 'tsx' ]

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source $HOME/.vim/rc/plugins/vim-airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#[[plugins]]
#repo = 'w0rp/ale'
#hook_add = 'source $HOME/.vim/rc/plugins/ale.rc.vim'

#[[plugins]]
#repo = 'powerline/powerline'
#rtp = 'powerline/bindings/vim/' 
#hook_add = 'source $HOME/.vim/rc/plugins/powerline.rc.vim'
